sudo: required
services:
  - docker

  before_install:
    - docker build -t przybytek/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run przybytek/react-test npm test -- --coverage

  after_success:
    - docker build -t przybytek/multi-client ./client
    - docker build -t przybytek/multi-nginx ./nginx
    - docker build -t przybytek/multi-server ./server
    - docker build -t przybytek/multi-worker ./worker
    # Log in to docker
    - ECHO "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push to docker
    - docker push przybytek/multi-client
    - docker push przybytek/multi-nginx
    - docker push przybytek/multi-server
    - docker push przybytek/multi-worker
